### ISSUE TITLE
[FEATURE] Headless benchmark

### ISSUE THREAD

**Issue by V10lator** [Guichaguri/BetterFps#119]
Hi, I'm using your mod on a le potato ( https://libre.computer/products/boards/aml-s905x-cc/ ). Ofc. I want as much resources for Java as possible, so the complete thing is flashed with a headless image and there's no input/output method except SSH (or UART). Now when I try to start BetterFPS standalone I get this:
```
libre@libre-computer:~/forge-server-1.12.2$ java -jar mods/BetterFps-1.4.8.jar
Loading en_us...
Waiting for Swing to load...
Exception in thread "main" java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
        at java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:807)
        at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:886)
        at java.awt.Toolkit.getEventQueue(Toolkit.java:1736)
        at java.awt.EventQueue.invokeLater(EventQueue.java:1294)
        at javax.swing.SwingUtilities.invokeLater(SwingUtilities.java:1295)
        at guichaguri.betterfps.installer.BetterFpsInstaller.main(BetterFpsInstaller.java:48)
```
So my question is: Could you please make at least the benchmarks available from headless? Maybe a simple startup argument like --headless (java -jar mods/BetterFps-1.4.8.jar --headless) will be enough?

**Comment by Enverex** [comment]
Would the server command option "nogui" work for you here?

EDIT: Apparently not. It looks like the performance is pretty much identical between all of them other than Java's own implementation though so I wouldn't worry about it.

![image](https://user-images.githubusercontent.com/958670/46144203-23e43580-c254-11e8-98ae-4efda81bc62c.png)

**Comment by Seathre** [comment]
+1 would be very nice to have.
