### ISSUE TITLE
forge will not find the 1.10 version of the mod and 1.11 will crash the game?

### ISSUE THREAD

**Issue by Super-Shot** [Guichaguri/BetterFps#28]
ok so i got the 1.11 version 1st and when i load the game up it crashed the game. So I went down to version 1.10 and was doing fine but when the game loaded up it was not in the mods tab and will not find it. If you can tell me how to fix this it would help a lot!

**Comment by Guichaguri** [comment]
For 1.11, can you please send me the crash log?
For 1.10, that's because of a missing feature in Forge, it loads my mod but doesn't add it to the list. I tried numerous times to add this feature to Forge, but they seem to not want it

**Comment by Super-Shot** [comment]
dont know how to put it in a file but this is it

2017-01-26 06:36:47,397 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2017-01-26 06:36:47,404 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[06:36:47] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[06:36:47] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[06:36:47] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[06:36:47] [main/INFO] [FML]: Forge Mod Loader version 13.20.0.2201 for Minecraft 1.11.2 loading
[06:36:47] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 8.1:amd64:6.3, installed at C:\Program Files (x86)\Minecraft\runtime\jre-x64\1.8.0_25
[06:36:47] [main/INFO] [FML]: Loading tweaker guichaguri.betterfps.tweaker.BetterFpsTweaker from BetterFps-1.3.3.jar
[06:36:47] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[06:36:47] [main/INFO] [LaunchWrapper]: Loading tweak class name guichaguri.betterfps.tweaker.BetterFpsTweaker
[06:36:47] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[06:36:47] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[06:36:47] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[06:36:47] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[06:36:52] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[06:36:52] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[06:36:52] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[06:36:52] [main/INFO] [LaunchWrapper]: Calling tweak class guichaguri.betterfps.tweaker.BetterFpsTweaker
2017-01-26 06:36:52,462 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2017-01-26 06:36:52,501 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2017-01-26 06:36:52,507 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[06:36:53] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[06:36:53] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[06:36:53] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[06:36:53] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[06:36:54] [main/INFO] [STDOUT]: [net.minecraft.client.main.Main:main:56]: Completely ignored arguments: [--nativeLauncherVersion, 307]
[06:36:55] [Client thread/INFO]: Setting user: Super_Shot
[06:36:56] [Client thread/INFO] [BetterFps]: Patching Minecraft using Riven's "Half" Algorithm
[06:36:58] [Client thread/INFO] [BetterFps]: Found 1 class patches for asn
[06:36:59] [Client thread/INFO] [BetterFps]: Found 1 class patches for aof
[06:36:59] [Client thread/INFO] [BetterFps]: Found 1 class patches for arz
[06:37:03] [Client thread/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/minecraft/tileentity/TileEntityFurnace.captureDroppedItems(Lnet/minecraft/tileentity/TileEntityFlowerPot;)Z @221: invokestatic
  Reason:
    Type 'net/minecraft/tileentity/TileEntityFlowerPot' (current frame, stack[1]) is not assignable to 'net/minecraft/inventory/InventoryLargeChest'
  Current Frame:
    bci: @221
    flags: { }
    locals: { 'net/minecraft/tileentity/TileEntityFlowerPot', 'net/minecraft/tileentity/TileEntityFurnace', 'net/minecraft/inventory/InventoryLargeChest', 'java/util/Iterator', 'net/minecraft/entity/item/EntityFallingBlock' }
    stack: { null, 'net/minecraft/tileentity/TileEntityFlowerPot', 'net/minecraft/entity/item/EntityFallingBlock' }
  Bytecode:
    0x0000000: 2ab6 020b 1202 a600 0a2a c000 02a7 0004
    0x0000010: 014c 2bc7 000a 2ab8 020f a700 072b b402
    0x0000020: 114d 2cc6 0074 b200 434e 2c2d b802 1699
    0x0000030: 0005 03ac 2cc1 0218 9900 372c c002 183a
    0x0000040: 0419 042d b902 1b02 003a 0503 3606 1506
    0x0000050: 1905 bea2 0019 2a2c 1905 1506 2e2d b802
    0x0000060: 1e99 0005 04ac 8406 01a7 ffe5 a700 282c
    0x0000070: b902 1f01 0036 0403 3605 1505 1504 a200
    0x0000080: 162a 2c15 052d b802 1e99 0005 04ac 8405
    0x0000090: 01a7 ffe9 a700 542b c600 0a2b b402 2199
    0x00000a0: 0049 2ab9 0227 0100 2ab9 022b 0100 2ab9
    0x00000b0: 022e 0100 0f63 2ab9 0231 0100 b802 34b9
    0x00000c0: 0237 0100 4e2d b900 5c01 0099 001d 2db9
    0x00000d0: 0060 0100 c002 393a 0401 2a19 04b8 023c
    0x00000e0: 9900 0504 aca7 ffe0 03ac               
  Stackmap Table:
    same_frame(@16)
    same_locals_1_stack_item_frame(@17,Object[#2])
    append_frame(@29,Object[#2])
    same_locals_1_stack_item_frame(@33,Object[#531])
    append_frame(@52,Object[#531],Object[#55])
    append_frame(@78,Object[#536],Object[#469],Integer)
    same_frame(@102)
    same_frame(@108)
    chop_frame(@111,3)
    append_frame(@122,Integer,Integer)
    same_frame(@142)
    chop_frame(@148,2)
    chop_frame(@151,1)
    same_frame(@162)
    append_frame(@197,Object[#89])
    append_frame(@229,Object[#569])
    chop_frame(@232,2)

	at net.minecraft.util.datafix.DataFixesManager.func_188279_a(DataFixesManager.java:243) ~[pi.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:343) ~[bes.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) ~[Main.class:?]
	... 6 more
Exception in thread "Client thread" [06:37:03] [Client thread/INFO]: [STDERR]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[06:37:03] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[06:37:03] [Client thread/INFO]: [STDERR]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[06:37:03] [Client thread/INFO]: [STDERR]: 	at java.lang.Runtime.exit(Runtime.java:107)
[06:37:03] [Client thread/INFO]: [STDERR]: 	at java.lang.System.exit(System.java:968)
[06:37:03] [Client thread/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[06:37:03] [Client thread/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)``

**Comment by Guichaguri** [comment]
You're using BetterFps for Minecraft 1.11 on Minecraft 1.11.2.
There's no BetterFps for 1.11.2 yet, I want to finish implementing my new patch system before updating it, so it will take a a bit longer.
