### ISSUE TITLE
If there is no config folder betterfps is not able to save its configuration file.

### ISSUE THREAD

**Issue by QuImUfu** [Guichaguri/BetterFps#50]
Under normal circumstances forge creates the config folder but BetterFps can be used without Forge and in this case it may need to create the folder itself.

important log part:
````
[20:01:30] [main/ERROR]: Could not save the config file
java.io.IOException: Datei oder Verzeichnis nicht gefunden
	at java.io.UnixFileSystem.createFileExclusively(Native Method) ~[?:1.8.0_121]
	at java.io.File.createNewFile(File.java:1012) ~[?:1.8.0_121]
	at guichaguri.betterfps.BetterFpsHelper.saveConfig(BetterFpsHelper.java:79) [BetterFpsHelper.class:?]
	at guichaguri.betterfps.BetterFpsHelper.loadConfig(BetterFpsHelper.java:74) [BetterFpsHelper.class:?]
	at guichaguri.betterfps.BetterFpsHelper.getConfig(BetterFpsHelper.java:23) [BetterFpsHelper.class:?]
	at guichaguri.betterfps.patchers.MinecraftPatcher.patch(MinecraftPatcher.java:25) [BetterFps-1.4.3.jar:?]
	at guichaguri.betterfps.transformers.Patch.patch(Patch.java:104) [BetterFps-1.4.3.jar:?]
	at guichaguri.betterfps.transformers.PatcherTransformer.transform(PatcherTransformer.java:59) [PatcherTransformer.class:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_121]
	at net.minecraft.client.main.Main.main(SourceFile:39) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:162) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:53) [NewLaunch.jar:?]
````
("Datei oder Verzeichnis nicht gefunden" means "file or directory not found")

**Comment by Guichaguri** [comment]
I definitely removed a line of code when I changed the config code. Thanks for reporting :)
