### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by JohnJohnJohnWhyisthisusernamestilltaken** [Guichaguri/BetterFps#93]
* Minecraft Version:1.12.2
* BetterFps Version: 1.4.8
* Forge/LiteLoader Version (if any): 14.23.0.2529
* Crash Logs (if any): 2017-11-04 16:01:12,284 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2017-11-04 16:01:12,288 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[16:01:12] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[16:01:12] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[16:01:12] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[16:01:12] [main/INFO] [FML]: Forge Mod Loader version 14.23.0.2529 for Minecraft 1.12.2 loading
[16:01:12] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_144, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_144
[16:01:12] [main/INFO] [FML]: Loading tweaker guichaguri.betterfps.tweaker.BetterFpsTweaker from BetterFps-1.4.5-1.10.jar
[16:01:12] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:01:12] [main/INFO] [LaunchWrapper]: Loading tweak class name guichaguri.betterfps.tweaker.BetterFpsTweaker
[16:01:12] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[16:01:12] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:01:12] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:01:12] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
2017-11-04 16:01:13,285 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2017-11-04 16:01:13,293 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2017-11-04 16:01:13,295 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[16:01:13] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[16:01:13] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[16:01:13] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:01:13] [main/INFO] [LaunchWrapper]: Calling tweak class guichaguri.betterfps.tweaker.BetterFpsTweaker
[16:01:14] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[16:01:14] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[16:01:14] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[16:01:14] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[16:01:14] [main/INFO]: Setting user: john
[16:01:15] [main/INFO] [BetterFps]: Patching net.minecraft.block.material.MaterialTransparent... (bcx)
[16:01:15] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/minecraft/block/material/MaterialTransparent.an()V @5: getfield
  Reason:
    Type 'net/minecraft/block/material/MaterialTransparent' (current frame, stack[0]) is not assignable to 'guichaguri/betterfps/patches/misc/MinecraftPatch'
  Current Frame:
    bci: @5
    flags: { }
    locals: { 'net/minecraft/block/material/MaterialTransparent' }
    stack: { 'net/minecraft/block/material/MaterialTransparent' }
  Bytecode:
    0x0000000: 04b3 0025 2ab4 002b bb00 2d59 b700 2fb9
    0x0000010: 0035 0200 57b8 003a b1                 

	at net.minecraft.block.material.Material.<clinit>(SourceFile:4) ~[bcz.class:?]
	at net.minecraft.block.BlockAir.<init>(SourceFile:16) ~[aom.class:?]
	at net.minecraft.block.Block.func_149671_p(Block.java:2238) ~[aow.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:498) ~[ni.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:364) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
	... 6 more
Exception in thread "Client thread" [16:01:15] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[16:01:15] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[16:01:15] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[16:01:15] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[16:01:15] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[16:01:15] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[16:01:15] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

* Other Mods (if any): nein

Yes one of these logs. All you need is top
---

**Comment by Guichaguri** [comment]
You're not using BetterFps 1.4.8, you're using BetterFps 1.4.5 for Minecraft 1.10
